{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "desafioDevops.fullname" . }}-db-credentials
  namespace: {{ .Values.desafioDevops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.host }}
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.user }}
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.password }}
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.database }}
{{- end }}
