{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.desafioDevops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    name: {{ .Values.desafioDevops.namespace }}
    {{- include "desafioDevops.labels" . | nindent 4 }}
{{- end }}
