{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.desafioDevops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    {{- if eq .Values.secretStore.provider "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.aws.serviceAccountName }}
    {{- else if eq .Values.secretStore.provider "vault" }}
    vault:
      server: {{ .Values.secretStore.vault.server }}
      path: {{ .Values.secretStore.vault.path }}
      version: {{ .Values.secretStore.vault.version | default "v2" }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStore.vault.authMountPath | default "auth/kubernetes" }}
          role: {{ .Values.secretStore.vault.role }}
    {{- end }}
{{- end }}
