#version: '3' -> Linha comentada para evitar warning, descomentar caso necessário e preferido pela empresa;
services:
    app:
        build:
            context: ./node
        container_name: app
        networks:
            - node-network
        tty: true
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "3000:3000"

    db:
        build:
            context: ./mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        environment: 
            - MYSQL_DATABASE=node_db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-network

    nginx:
        build:
            context: ./nginx
        container_name: nginx
        depends_on:
            app:
                condition: service_healthy
        networks: 
            - node-network
        ports: 
            - "8080:80"

networks:
    node-network:
        driver: bridge
