desafioDevops:
  replicas: 3
  namespace: desafioDevops-prod
  namespace:
    create: true
  image: 585534523398.dkr.ecr.us-east-1.amazonaws.com/desafioDevops:production
  imagePullPolicy: IfNotPresent
  port: 3000
  imagePullSecrets:
    - name: ecr-secret
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  probes:
    enabled: true
    path: /health
    startup:
      failureThreshold: 180
      periodSeconds: 1
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 180
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
  ingress:
    path: /desafioDevops(/|$)(.*)
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# External Secrets Operator Configuration
externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aws-secrets-store-prod
  targetSecretName: db-credentials
  remoteKeys:
    host: desafioDevops-prod/host
    user: desafioDevops-prod/user
    password: desafioDevops-prod/password
    database: desafioDevops-prod/database

# SecretStore Configuration (AWS Secrets Manager)
secretStore:
  enabled: true
  name: aws-secrets-store-prod
  provider: aws
  aws:
    region: us-east-1
    serviceAccountName: external-secrets-sa
